### PR TITLE
Update hash

### PR DESCRIPTION
**Pull request by tcoopman**

### CODE REVIEW

**Comment by scohen** [comment]
@hauleth I thought this was automatic now.

**Comment by hauleth** [comment]
Should be, but it seems that something did not work as expected. I will check. Testing GitHub Actions suck.

**Comment by scohen** [comment]
it sure does. Anything I can do to help, @hauleth ?

**Comment by scohen** [comment]
@hauleth any updates on this?

**Comment by wingyplus** [comment]
From https://github.com/lexical-lsp/lexical/actions/runs/6898983605/job/18769850544#step:5:12, it seems we forgot to add some permission to allows github-bot to push to this repository.

**Comment by hauleth** [comment]
Seems that would be a solution. Though IIRC that was working perfectly fine in my repos where I use something similar to handle `CHANGELOG` updates.

**Comment by scohen** [comment]
giving a bot push permissions seems like a really bad thing, no?

**Comment by hauleth** [comment]
I use it for automatic generation of `CHANGELOG` in some of my projects and find it acceptable solution. Though it is up to you if you.

**Comment by zachallaun** [comment]
@scohen Lots of projects use bots to push commits, many official Elixir repos included. I'm not concerned.

**Pull request closed without merging**
