### PR TITLE
Update nix mix deps sha256

### PR DESCRIPTION
**Pull request by zoedsoupe**
On commit 2178b4b there was an update to dialyzer mix dependency. That causes a new state for `mix.lock` and therefore a new sha256 hash for the mix FOD deps build with `nix`.

### CODE REVIEW

**Comment by scohen** [comment]
@hauleth the detection scripts don't seem to be working.

**Comment by skbolton** [comment]
I am starting to think that it would be better to not try and have the nix definition stay up to date with main. It could make more sense to go to a release model and pin a tag and then as part of the release process update the nix definition.

**Comment by scohen** [comment]
I fixed the permissions error. The other error doesn't look like anything to me.

**Comment by scohen** [comment]
One reason is that main isn't in a great state right now

**Comment by skbolton** [comment]
Sounds good @scohen.just wanted to make sure you weren't thinking things were resolved by the action fix.

**Comment by hauleth** [comment]
Ahh, yeah. I need to update the script a little, as it is expected to fail, so it should take that into the account.

**Comment by hauleth** [comment]
#683 supersedes this PR

**Comment by scohen** [comment]
Closing in favor of #683

**Pull request closed without merging**
