### PR TITLE
Added a changelog

### LINKED ISSUE #626: Adding a CHANGELOG
I'd like to see a `CHANGELOG.md` in this repository to have a better understanding of features/improvements/fixes & more at each new versions :heart:

Maybe using something like [convertional commits](https://www.conventionalcommits.org/en/v1.0.0/) can help :smiley:

### PR DESCRIPTION
**Pull request by scohen**
Fixes #626

### CODE REVIEW

**Comment by scohen** [comment]
Note, this is just copied release notes.

**Comment by zachallaun** [comment]
My only additional thought is that it would be nice to automate this somehow, since the "What's Changed" portion is generated from commits to `main`.

**Comment by scohen** [comment]
> My only additional thought

Yep, let's investigate this.

**Comment by crbelaus** [comment]
Google provides a GitHub action called [Release Please](https://github.com/google-github-actions/release-please-action) which can automate the CHANGELOG and release generation.

> Release Please automates CHANGELOG generation, the creation of GitHub releases, and version bumps for your projects. Release Please does so by parsing your git history, looking for [Conventional Commit messages](https://www.conventionalcommits.org/), and creating release PRs.

I have not used it in any of my projects yet as they are kind of small and don't have many releases but I know that it supports Elixir and it is used in multiple Elixir projects such as [NextLS](https://github.com/elixir-tools/next-ls/blob/main/.github/workflows/release.yaml).

Not saying that this is the only or even the best tool but just wanted to point out its existence in case it may be helpful.

**Pull request merged**
